### ISSUE TITLE
How do you read git api page more than 1344?

### ISSUE THREAD

**Issue by xiejiachen** [seladb/StarTrack-js#18]
Dear Author:

I am a student working on my paper, I also wanna to count github stars.
My plan is to use 
`https://developer.github.com/v3/activity/starring/#alternative-response-with-star-creation-timestamps`

But it only works with 1334 pages limit, and I can only plot the trends at repo less than 5000 stars.

How can your job so great deal with popular repo

**Comment by seladb** [comment]
thanks for reaching out @xiejiachen.

Due to [GitHub's rate limiter](https://developer.github.com/v3/#rate-limiting) a user is blocked after a certain number of API calls. I believe this number is 60 per hour.

In order to increase this limit a user can provide a GitHub access token which is passed in the `Authorization` header of the API call. A user can create an access token through this page: https://github.com/settings/tokens

Here is a reference to the code that creates and sends the API calls and also handles passing the access token to them:
https://github.com/seladb/StarTrack-js/blob/672b334c82334be4934e747c1801bd1f26ce4e6b/src/utils/GitHubUtils.js#L50

I hope that makes sense. Please let me know if you have further questions.

**Comment by seladb** [comment]
I'm closing this issue now, please reopen if needed
