### ISSUE TITLE
Pagination limit reached when graphing denoland/deno

### ISSUE THREAD

**Issue by Byron** [seladb/StarTrack-js#30]
When entering https://github.com/denoland/deno into https://seladb.github.io/StarTrack-js it will load the star history nearly to the end until this message appears:

<img width="619" alt="Screenshot 2021-10-11 at 08 01 45" src="https://user-images.githubusercontent.com/63622/136717319-f6c24fcc-bbe2-43b7-8f82-eca3259efb61.png">

It suggests to check the `rel=last` response header to handle the issue gracefully. Then all already retrieved results, nearly 100% according to the progress bar, are discarded.

A way to solve this issue might be to…

* …rely on `rel=last` as suggested
* …graph the successfully retrieved star history despite the error, instead of discarding it.

**Comment by theMasix** [comment]
Same issue here for [vercel/next.js](https://github.com/vercel/next.js)

**Comment by seladb** [comment]
@Byron @theMasix I'm really sorry for the late response. You're right, that's a good idea! We can also let the user choose between not displaying anything and displaying the successfully retrieved data. Another option (that I need to check if possible) is to retrieve the latest data, meaning instead of starting from page 1 - start with the minimum page that allows fetching all of the data until the present time.

If you have time to work on this - I'd really appreciate it if you can open a PR. Otherwise, I'll try to make time for it, but I can't guarantee when...

**Comment by seladb** [comment]
The issue has been fixed in [version 3.0.0](https://github.com/seladb/StarTrack-js/releases/tag/v3.0.0).

I also added a check for the star count and a warning if couldn't load all stars in this PR: https://github.com/seladb/StarTrack-js/pull/70. It'll be released soon, as part of version 3.1.0
